spring:
  application:
    name: data-tracker

sampling:
  # every minute
  cron: 0 * * * * ?
  frequency: 6000000

kafka:
  producer:
    topic: samples
    properties:
      bootstrap.servers: localhost:9092
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: io.confluent.kafka.serializers.KafkaJsonSerializer

  streams:
    input: ${kafka.producer.topic}
    output: statistics
    properties:
      application.id: ${spring.application.name}
      bootstrap.servers: ${kafka.producer.properties.bootstrap.servers}
