kafka:
  producer:
    topic: samples
    properties:
      bootstrap.servers: localhost:9092
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: io.confluent.kafka.serializers.KafkaJsonSerializer

sampling:
  # every minute
  cron: 0 * * * * ?
  frequency: 60000
